export type Car = {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number; // USD
  zeroSixty: number; // seconds
  topSpeedMph: number;
  horsepower: number;
  torqueLbFt: number;
  engineId: string; // links to engines.ts
  drivetrain: "RWD" | "AWD" | "FWD" | "MR";
  transmission: string;
  weightLbs: number;
  bodyType: "Coupe" | "Sedan" | "SUV" | "Roadster" | "Hypercar";
  segment: "Track" | "Grand Tourer" | "Hypercar" | "Electric" | "SUV";
  production: string;
  designer?: string;
  origin: string;
  blurb: string;
  highlights: string[];
  img: string;
};

export const CARS: Car[] = [
  {
    id: "ferrari-sf90",
    make: "Ferrari",
    model: "SF90 Stradale",
    year: 2024,
    price: 625000,
    zeroSixty: 2.5,
    topSpeedMph: 211,
    horsepower: 986,
    torqueLbFt: 590,
    engineId: "phev-v8tt",
    drivetrain: "AWD",
    transmission: "8-speed dual-clutch",
    weightLbs: 3461,
    bodyType: "Coupe",
    segment: "Hypercar",
    production: "999 units",
    designer: "Flavio Manzoni",
    origin: "Maranello, Italy",
    blurb:
      "The first series-production Ferrari with PHEV architecture. A 4.0L twin-turbo V8 is paired with three electric motors for a combined 986 hp and a 2.5-second sprint to 60.",
    highlights: [
      "Plug-in hybrid powertrain",
      "Carbon-fibre monocoque",
      "Active aero with rear wing",
      "0–60 in 2.5 s",
    ],
    img: "/images/cars/ferrari-sf90.jpg",
  },
  {
    id: "bugatti-chiron",
    make: "Bugatti",
    model: "Chiron Super Sport",
    year: 2024,
    price: 3900000,
    zeroSixty: 2.4,
    topSpeedMph: 304,
    horsepower: 1577,
    torqueLbFt: 1180,
    engineId: "w16-quad",
    drivetrain: "AWD",
    transmission: "7-speed dual-clutch",
    weightLbs: 4365,
    bodyType: "Hypercar",
    segment: "Hypercar",
    production: "Limited 100",
    designer: "Jozef Kabaň",
    origin: "Molsheim, France",
    blurb:
      "An 8.0L quad-turbocharged W16 producing 1,577 hp. Long-tail bodywork, active rear wing, and 304 mph capability. Engineering as theatre.",
    highlights: [
      "Quad-turbo W16",
      "304 mph top speed",
      "Carbon-fibre body panels",
      "1 of 100",
    ],
    img: "/images/cars/bugatti-chiron.jpg",
  },
  {
    id: "porsche-911-gt3",
    make: "Porsche",
    model: "911 GT3 (992)",
    year: 2024,
    price: 192900,
    zeroSixty: 3.2,
    topSpeedMph: 198,
    horsepower: 502,
    torqueLbFt: 346,
    engineId: "flat6-na",
    drivetrain: "RWD",
    transmission: "7-speed PDK / 6-speed manual",
    weightLbs: 3168,
    bodyType: "Coupe",
    segment: "Track",
    production: "Ongoing",
    designer: "Michael Mauer",
    origin: "Stuttgart, Germany",
    blurb:
      "A naturally aspirated 4.0L flat-six screaming to 9,000 rpm. The benchmark rear-engine track tool, with motorsport DNA engineered into every component.",
    highlights: [
      "9,000 rpm redline",
      "Dual-clutch PDK",
      "Rear-wheel steering",
      "Motorsport-derived suspension",
    ],
    img: "/images/cars/porsche-gt3.jpg",
  },
  {
    id: "tesla-model-s-plaid",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 109990,
    zeroSixty: 1.99,
    topSpeedMph: 200,
    horsepower: 1020,
    torqueLbFt: 1050,
    engineId: "ev-tri",
    drivetrain: "AWD",
    transmission: "Single-speed (front) + 2-speed (rear)",
    weightLbs: 4766,
    bodyType: "Sedan",
    segment: "Electric",
    production: "Ongoing",
    origin: "Fremont, USA",
    blurb:
      "Three carbon-sleeved electric motors. 1,020 hp. The fastest production sedan ever built — 0–60 in under 2 seconds with a drag strip on every drive.",
    highlights: [
      "Tri-motor all-wheel drive",
      "1.99 s 0–60",
      "405 mi range",
      "17-inch cinematic display",
    ],
    img: "/images/cars/tesla-plaid.jpg",
  },
  {
    id: "lamborghini-revuelto",
    make: "Lamborghini",
    model: "Revuelto",
    year: 2024,
    price: 608000,
    zeroSixty: 2.5,
    topSpeedMph: 217,
    horsepower: 1001,
    torqueLbFt: 791,
    engineId: "phev-v12-na",
    drivetrain: "AWD",
    transmission: "8-speed dual-clutch",
    weightLbs: 3873,
    bodyType: "Coupe",
    segment: "Hypercar",
    production: "Limited annual",
    designer: "Mitja Borkert",
    origin: "Sant'Agata Bolognese, Italy",
    blurb:
      "The successor to the Aventador: a 6.5L naturally aspirated V12 paired with three electric motors. The last of its kind, the loudest of them all.",
    highlights: [
      "Naturally aspirated V12",
      "1,001 hp hybrid",
      "Carbon-fibre monofuselage",
      "Active aerodynamics",
    ],
    img: "/images/cars/lambo-revuelto.jpg",
  },
  {
    id: "mclaren-750s",
    make: "McLaren",
    model: "750S Spider",
    year: 2024,
    price: 345000,
    zeroSixty: 2.7,
    topSpeedMph: 206,
    horsepower: 740,
    torqueLbFt: 590,
    engineId: "v8-tt-mc",
    drivetrain: "RWD",
    transmission: "7-speed SSG",
    weightLbs: 3131,
    bodyType: "Roadster",
    segment: "Track",
    production: "Ongoing",
    designer: "Rob Melville",
    origin: "Woking, UK",
    blurb:
      "Lighter, faster, and more agile than the 720S it replaces. Mid-engine twin-turbo V8, retractable hard-top, and a hydraulic Proactive Chassis Control III suspension.",
    highlights: [
      "Mid-engine twin-turbo V8",
      "Retractable hard-top",
      "Carbon-fibre tub",
      "Proactive Chassis Control III",
    ],
    img: "/images/cars/mclaren-750s.jpg",
  },
  {
    id: "aston-martin-db12",
    make: "Aston Martin",
    model: "DB12 Volante",
    year: 2024,
    price: 286000,
    zeroSixty: 3.6,
    topSpeedMph: 202,
    horsepower: 671,
    torqueLbFt: 590,
    engineId: "v8-tt-am",
    drivetrain: "RWD",
    transmission: "8-speed auto",
    weightLbs: 3968,
    bodyType: "Roadster",
    segment: "Grand Tourer",
    production: "Ongoing",
    designer: "Marek Reichman",
    origin: "Gaydon, UK",
    blurb:
      "A hand-built grand tourer with a 4.0L twin-turbo V8 from AMG and an electronically limited slip differential. The super tourer reimagined.",
    highlights: [
      "4.0L twin-turbo V8",
      "8-layer fabric roof",
      "Adaptive dampers",
      "Bowers & Wilkins audio",
    ],
    img: "/images/cars/aston-db12.jpg",
  },
  {
    id: "rimac-nevera",
    make: "Rimac",
    model: "Nevera",
    year: 2024,
    price: 2400000,
    zeroSixty: 1.81,
    topSpeedMph: 258,
    horsepower: 1914,
    torqueLbFt: 1741,
    engineId: "ev-quad",
    drivetrain: "AWD",
    transmission: "4 independent single-speed",
    weightLbs: 4784,
    bodyType: "Coupe",
    segment: "Electric",
    production: "150 units",
    origin: "Sveta Nedelja, Croatia",
    blurb:
      "Four permanent-magnet motors, 1,914 hp, and a 120 kWh battery. The fastest-accelerating production car in the world — 0–60 in 1.81 seconds, verified.",
    highlights: [
      "Quad-motor 1,914 hp",
      "1.81 s 0–60",
      "Carbon-fibre monocoque",
      "Rimac All-Wheel Torque Vectoring",
    ],
    img: "/images/cars/rimac-nevera.jpg",
  },
  {
    id: "koenigsegg-jesko",
    make: "Koenigsegg",
    model: "Jesko Absolut",
    year: 2024,
    price: 3000000,
    zeroSixty: 2.5,
    topSpeedMph: 330,
    horsepower: 1600,
    torqueLbFt: 1106,
    engineId: "v8-tt-kg",
    drivetrain: "RWD",
    transmission: "9-speed Light Speed Transmission",
    weightLbs: 2998,
    bodyType: "Hypercar",
    segment: "Hypercar",
    production: "125 units",
    designer: "Christian von Koenigsegg",
    origin: "Ängelholm, Sweden",
    blurb:
      "A 5.0L twin-turbo V8 on E85 biofuel producing 1,600 hp. Engineered to break the 500 km/h barrier. The world's first 9-speed multi-clutch transmission.",
    highlights: [
      "1,600 hp on E85",
      "Target 330+ mph",
      "Carbon-fibre wheels",
      "9-speed Light Speed Transmission",
    ],
    img: "/images/cars/koenigsegg-jesko.jpg",
  },
  {
    id: "rolls-spectre",
    make: "Rolls-Royce",
    model: "Spectre",
    year: 2024,
    price: 422000,
    zeroSixty: 4.4,
    topSpeedMph: 155,
    horsepower: 577,
    torqueLbFt: 664,
    engineId: "ev-dual",
    drivetrain: "AWD",
    transmission: "Single-speed automatic",
    weightLbs: 6559,
    bodyType: "Coupe",
    segment: "Electric",
    production: "Ongoing",
    origin: "Goodwood, UK",
    blurb:
      "The first fully electric Rolls-Royce. A super-luxury coupe delivering silent, effortless grand touring with 329 miles of range and 577 twin-motor horsepower.",
    highlights: [
      "First electric Rolls-Royce",
      "Spirit OS infotainment",
      "Starlight Doors with 4,796 stars",
      "329 mi range",
    ],
    img: "/images/cars/rolls-spectre.jpg",
  },
  {
    id: "g63-amg",
    make: "Mercedes-AMG",
    model: "G 63 4x4²",
    year: 2024,
    price: 195000,
    zeroSixty: 4.7,
    topSpeedMph: 137,
    horsepower: 577,
    torqueLbFt: 627,
    engineId: "v8-tt-am",
    drivetrain: "AWD",
    transmission: "9-speed AMG Speedshift",
    weightLbs: 6096,
    bodyType: "SUV",
    segment: "SUV",
    production: "Limited",
    origin: "Affalterbach, Germany",
    blurb:
      "Hand-built 4.0L twin-turbo V8 in a portal-axle off-road super-SUV. The most uncompromising G-Class ever produced, equally at home in Monaco or the Sahara.",
    highlights: [
      "Portal axles",
      "Twin-turbo V8",
      "Three locking differentials",
      "Forged carbon-fibre trim",
    ],
    img: "/images/cars/g63-4x4.jpg",
  },
  {
    id: "porsche-taycan-turbo-gt",
    make: "Porsche",
    model: "Taycan Turbo GT",
    year: 2024,
    price: 230000,
    zeroSixty: 2.2,
    topSpeedMph: 190,
    horsepower: 1019,
    torqueLbFt: 988,
    engineId: "ev-dual",
    drivetrain: "AWD",
    transmission: "2-speed auto (rear)",
    weightLbs: 5015,
    bodyType: "Sedan",
    segment: "Electric",
    production: "Limited annual",
    origin: "Stuttgart, Germany",
    blurb:
      "The most powerful production Porsche ever. Two-speed rear gearbox, push-to-pass overboost, and a Nürburgring lap record holder. Voltage, properly channeled.",
    highlights: [
      "1,019 hp with overboost",
      "Nürburgring EV record",
      "Carbon-fibre body kit",
      "800V architecture",
    ],
    img: "/images/cars/taycan-turbo-gt.jpg",
  },
];

export function getCar(id: string): Car | undefined {
  return CARS.find((c) => c.id === id);
}

export const MAKES = Array.from(new Set(CARS.map((c) => c.make))).sort();
export const SEGMENTS = Array.from(new Set(CARS.map((c) => c.segment))).sort();
export const BODY_TYPES = Array.from(new Set(CARS.map((c) => c.bodyType))).sort();
